# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.  
language: c

env:
  global:
  - GHC_VERSION=7.10.3
  - secure: "sxjRE66hHIgjzTc1QBj3TqC9WDWgwEni+poeJ3KNlNYrjlVOfKPoQBR1ZuEdhc7dXpplng9BMovHYuodeFk4IbA8UnfmEhHYlIMS6fJe0hzxo0VW8bckTHkxQWhGc85hCy95yAFVEP+cwcxKh7YbKmgryETbRvFCbO6kOl67QS5j77ADafWjFgnGV0y1aJypZw3ZgYQN7rMHRxPxLfQlAg27JYgKqre5iftWhuyorkvzJXRgl3k1M+YiAZwBY2T8pj36730GJJAe9akD+Px6Gi75kvHb30t5sfIg/2Nnldbqo7OnoecS7/VfuJjL3WxA3UjsHBT7LGUwtIvrzfwx3tRt8jmJTHIOrTIHGirLFt9lPVcBGBrnsBfD7L4j2MFV8xVYrx/45DgOLR7FRbjGxoShjwOwFhNBIWLVTtzl269t2hKvrrnmc5w9lSuct9l7agYV32IWNK1B9NEAsboPHE+JsrANsnxSITKlYI5a3var8/3P69t/rwLEJnFmlM21pvJ8iBYT7uzFRxyT/Yxdm8TTs2xvGshTlmUV2uaj1wnhCOwjtLq97zfvl/lSR+vuQ6gfPmNUSgl7O1gMcdEW9HngpErcwc35Kf6urwtwehYgMrsd9zEeUvBPWElnHREwqiE8vNdHNnCwcnzKfpYUELf9ISSNB9pvPQ4e3pw7LqE="

branches:
  only:
    - source

#Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:/opt/ghc/$GHC_VERSION/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-head
      - ghc-7.10.3

#install:
#  - stack --no-terminal setup  

script:
  - stack --no-terminal build

after_script:
  - cd _site
  - git config --global user.email "$GIT_EMAIL"
  - git config --global user.name "$GIT_NAME"  
  - export REMOTE=$(git config remote.origin.url | sed 's/.*:\/\///')
  - git remote add github https://${GH_TOKEN}@${REMOTE}
  - git add --all
  - git status
  - git commit -m "Built by Travis ( build $TRAVIS_BUILD_NUMBER )"
  - git push github master:master | grep -v http

