# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.    
language: c
env:
  global:
  - secure: "jDktdEylRLpUfLXfAgI7SR1/L1fG8RjC2JonNlMC7HGu8UokTPPoMJ4ephXEax6nCxEex96DLSxP1mNs8HKajMuuAXrZeoDjUMI6PI8Y0q2t5nO4aaVqQ67mWK7PHlsR650nwSLhvetrfX9My3+80pLYR4PN1Ct/ASIlaeiAIWhbWlVgUPMKIL1KEBCiO5vcNpp/8nWgbHgyDJtA6ewcwuYVve+gbFcCT/yiIMbpi9zGbob7KMOcKUShKfN37UmS2Z6BhCXSoSOh9pjvZtDZuRK+tmTJBMbiy1m5oxObKTKSj2sBpsXq0nsTgrfkHbLZKAdEN/oiijn6jnol06FOhcEl8fGD+nTKRTO+bd7P9+5rZwM+I78mviQb4D/oeTUQcWjWIJdoGRtRHd8bC/1jU7EBUTRYlfSGscHCb/3Ba2XhZcYlhedz4u0/DJ7SQ71LCpKQ4ybV8UDypkd9ZvdPrHitDbSrQcZZQo6KsB/cOKAzrZPfM+7HpQ+Yupw6R5V0zfC0oy69AuXN+yyqHYafWxe/O3D02j46bFELI94d44xamzfdT+3OFXeuvw2/+E6AylZEIwOoR9N7vfc+d+WVSJLd6s9WXf4H1SX9reZxhq4jgB7mSins75bt/5D7tx7LJkTNyRBzEPyDJJ8EucHEz4isrEJzDAORfe++dFgFp6M="
  
branches:
  only:
  - source

#Caching so the next build will be fast too.    
cache:
  directories:
  - "$HOME/.stack"

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -sSL https://get.haskellstack.org/ | sh

install:
- stack --no-terminal setup

# steps till script are cached. we prepare the environment here.
script:
- stack path
- stack --no-terminal build

after_script:
- stack --no-terminal exec site build
- cd _site
# Adding a CNAME file, so our custom domain works with github 
- echo "blog.${GH_USER}.com" > CNAME  
- git config --global user.email "$GH_EMAIL"
- git config --global user.name "$GH_NAME"
- export REMOTE=$(git config remote.origin.url | sed 's/.*:\/\///')
- git init  
- git remote add github https://${GH_USER}:${GH_TOKEN}@${REMOTE}
- git add --all
- git status
- git commit -m "Built by Travis ( build $TRAVIS_BUILD_NUMBER )"
# We don't care about commits to the master as a completely new site would be generated everytime  
- git push github master:master -f 2>&1 | grep -v http

notifications:
  email:
    recipients:
      - chopra.shubham+travis@gmail.com
    on_success: always
        
