# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.  
language: c

env:
  global:
  - GHC_VERSION=7.10.3
  secure: "bZtWEPeaXcRUS/g6smXPW3ji5jz5i1OuSlNSz0SuU6W52cKJfsq7ZYt9jBGx5e6K90jBVVmk11LQJOtUNvxHVh3WlfT6jzpIheYOkBGEYTpjEW/tHH3d3A+i/udDIA29wtz11ro0LqYSIQbI4r4nZiYPv/vI4NrUzZNl6Kou8kwcyDJVVdlyHX/ANCfQ2KQsW+GTqTKTG3DxrmY1bNe9AGW/W9M1kMaRhzvtRtOQHSmQbbQoYm/WtnJpDPvAeK20nPd7v6IQQJOb4PWgLLsu1O9RoUjvPVulTHcLGusZJrphLnsJs89UENfgTAwNyd2FuInXcKgDw6qyniBHCg4d0vuwmMhkSAYdBnZNLAzdfMt8qfK7b2LsSysbNK4qiKvMolrd5GAOgTWOEIWcrOvsZ2sINXGSaYLba07dzkWJeHyG8QntvyqO2d2Gi3W0tLd0gfQRFyFHdjUxIHSJ/gGKU9Suydfpt3yF+HbBfSf7iromctsdUAV4+yLuJeOvrqzg/Cr+gjiDe13aRu0SJxBqUNywgY6KwATFyp7Q1MgeNZQlebMgcsA5Tc4Of51KPXDhWImSPt94oLJHX7MLe79/sTQuUodlk0mGG3EU2rskYEptSoX+1weD25aDkxUsD97kA4zVF6bB0YunYTDaDqNfT+KhtiVUqKWQPfi2Gx2awac="

branches:
  only:
    - source

#Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:/opt/ghc/$GHC_VERSION/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-head
      - ghc-7.10.3

install:
  - stack --no-terminal build  

script:
  - stack --no-terminal exec site build

after_script:
  - cd _site
  - ls -al  
  - git --version  
  - git status  
  #Travis detaches the head, so we reinitialize git inside _site/  
  - export REMOTE=$(git config remote.origin.url | sed 's/.*:\/\///')
  - git init  
  - git config --global user.email "$GH_EMAIL"
  - git config --global user.name "$GH_NAME"  
  - git remote add github https://${GH_USER}:${GH_TOKEN}@${REMOTE}
  - git add --all
  - git status
  - git commit -m "Built by Travis ( build $TRAVIS_BUILD_NUMBER )"
  - git push github master:master | grep -v http

