# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.  
language: c

env:
  global:
  - GHC_VERSION=7.10.3
  secure: "T7DoPtKGjjwntUss5Srg+XRUjy6uXDC2lnEckfsfPf1b9zg6PlCLSz2UoCIYBW+9LoGhGuBD9yd+RRsHswBWbl5+EsnJU+bGTp29kFpq9AVN35rMS9/lYbTgJDYko7HGfHKB33rw/OsLoBJulbKbafl+SwaYBGAsTwIwrtqg4r1TZI3ToREzak6oTitEbAaQa3khSt/Lw+/eZd97tWs1zzgwG/hMwBN5XZqxHsfQOrXyyMHUm1wMaQ+X3ASyx3zGDqAPhqr/mipxyvhRuL7nEN+OEu4PO4TYaVaGP6uE+6oD0izgsFrOxwlZJCPuw1o/E5L+3HKWTN5tm6mnthax+T0LtzNrM2BNBtHQHIHoBtrGnfc7xIfn5876zMOPOCrB5aqrY/2wRrRzXIOJXkOJZDKRapENoMZ2bDjS4TSSMFXYdy9oxlFRzpEbKtQh0j1Ch3InB/A8I7VWL0SKMDqSvElPKTH4jhebt04JzKniD16kpJrMIaJK6f7U5yOM4O0UIYv9cefUo5wBcZtMdholP7kFzodB6qYGM7QUmT3uJ5dUUu1e7hFl+cDXOgdbyfN/5CH2ydJG06+qDVNr9iXe1XVZ1cr2W1d/oUHSgXSucpkNK4juM7OwNW2yJUBTMnDI+usIFCZHp4hAbwN3x7wPV4/GlVT2CXRxmhGCPYsHGCI="

branches:
  only:
    - source

#Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:/opt/ghc/$GHC_VERSION/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-head
      - ghc-7.10.3

install:
  - stack --no-terminal build  

script:
  - stack --no-terminal exec site build

after_script:
  - cd _site
  - ls -al  
  - git --version  
  - git status  
  #Travis detaches the head, so we reinitialize git inside _site/  
  - export REMOTE=$(git config remote.origin.url | sed 's/.*:\/\///')
    #  - git init  
  - git config --global user.email "$GH_EMAIL"
  - git config --global user.name "$GH_NAME"  
  - git remote add github https://${GH_USER}:${GH_TOKEN}@${REMOTE}
  - git add --all
  - git status
  - git commit -m "Built by Travis ( build $TRAVIS_BUILD_NUMBER )"
  - git push github master:master | grep -v http

