# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.  
language: c

env:
  global:
  - GHC_VERSION=7.10.3
  secure: "n6z2j5X9nQoXoJFNXXr8iKUb4jbQ9W2QtlL4vWts+HQLUmJgoi9aPLXm52HR2QqdiYYU9sZX7u0hR3zvCbMnLsCbxjpjHMoAJvDLW4BGoAr7RFieTcA6pH6OgIHJuj5C5UuBQvU/nk2k2NbQJupZBSi4orlP09bYbflfp7wceogd0cuxJSWiJx+XPOrO434rLv4hv8yRiGevxx+bug4RgMSNS2AjNFBd+KEgfsSXtQ8M2YfwtSnGDxNPXtuV4DEeHvQooQmY0/8icX09IczXTQKeN0WKhDko6ozy+2D4aXUK30vZvX6zzd/uX3I+0noY7z/LrJlyGjaSJaRDU18Udd/6iMAbS6MWnHuS3cnrqYEMDco18JUQaoQlFR2S8oQot2b/VcKnC0h0mnKcYCff9dCyKClojgBsrgdkDX4rk55Tnnw0IoLg1oMz2D1Wl8zICHQdhBq/lDsiL6vm1eyu6zGa/+yFBzzo1/4dl1dWGrrHKyTCu7t4NdjsFJVgsiI5FPQphFYqRloDPD1mNuWZazU02cmP9ZonnOdQbG1OTFO3oJTA6BzShflFbOGcK72DbMAjXJwNXZxIDA4MpO7Ul8mGZ9xCnHHkICVnf9M+/r/Km1ltcxx02vV4sTzB9ziREePImQX4A66f8AkHKnSitPI2Wxs39oAt85g8MvH5kuY="
  secure: "S7tcOGKfzgtq5/wPz1gSpOpah53ic+rgagVsUNlsqu8BorWXbGX9rMQC2I/zDMDD8VmTEfb2FClXr9j3fkYnHSfA/3zZ4fSV0B0GOxAeGbhTpV0xlez5isQ8y+5mgVue58K9U3gYyUqwaDhqtsPcf6EWizXB1ywUllxlsl6K7g0q1Phd1y2nthXDHPlNQiRm/iwWYml+osrweyN9y0zk4HsWsP07IouaIgwq7GK/qIjMzv7jnBDvJm/bQ2JFykkYumz3mBdZt7fC/ogyHYtRqJzrUn9CFuNq+FCatFsUTJtNl1xSSDUz3LdNLbI+eD3taFfGB+kG+lRVZHfLxZsDwpxhLj/6C3LJp+1X/ir3+a7mESmXi9BSR1Ud1drSHYbIje4Ukk4lsyH6qcRths9SmZhZ6aWxl0YIIbMdebZJBs17LFer1ltmaGzX6dKdd3S/wEIa74QA53tpq6HWchQniSDTrgHdMb2WiouN4A1c1vL6RunaM1cBgEA/oPsAjJzoPBiSUFPPdjZh1HIhedCX7brQOy0mh4O+/gyUtj7Xh+VWbMGm2+ZZWQYwlxJHH35Y6OMKtQS3FA9RXDx8x7R77xdzaDA2ta+LgyDeFX4nTWOThqzY4BY5G9WVsoFm1cT1JRw5QerpQwB/z1qr9ZmOdUqeszw9wdQmUTEQSvL34Bk="  
  secure: "FwnZ1hilprn+M/e/2/qb8Gyeea2132NS8Tl4WZdu0mrZfH1wxUOlsFrJKD1cEaZGtCrmlt+UNRgPkRdEeQgWg8ZsliAXCBR5xbhmH/8JH//CszwGZ6n7P/Vx2V2dvfydHQi0bMzBpCM9t3QtpCac7G21slWU0x7iWnBA9B76jQrHfI4obiJ0TqfW15JNEjGuwJbOTWzmPFkENxTZBI10MO5CKS4NdbK6PcRKAvEJnSzWp1H5xtJxXlPctqR2cVfeUUwq6M7Q8kUcmtdDxn/uWPqrKjeOKbzVpEGgIiia1CE6TRULrBk02t5+lpanTexMbpyUSGBbl1gViXqJunqM+Tx8SxwTrRsAh+h4A/yP7/FXoCHbUadoj7a4VatBY8N41UBzRcKowITzLIx14n7yUbF9O6ggqhH+zZBkJilnpiMVa1MOpEYp6oM9lKwGigrbnbqEO+xP0vxwW9F8stH6WkegMgEI/TXs9P+Pjqdkvmi8T+4o32xoEOQFvQieGpqvlToH+TmxO5swufyLR3ZsLC7PPGbhIV6+FL+caw79UKre9GTacKxSH9RtPCF93EVtKhn2/Qt2/hvWrOYkRSCcfmWAfkSIYzz4zqg0yRlDA903TxWpF27JCvSZPE94rogK8OBJpsPpcK9RdkWJUALDm/CdDFs7+tOTk2H/u2USsRM="
  secure: "LSHjMD7RoeFU/jp+ID0Tkr6SI+W1nmrK1sMAv1PQzcA+V800Ix/F6/5E5KmA0ObXE4kknJtp7a8vxAECcIoNLc4GwSfU+b57ANKYBdWufrY4HFTJA4Tsrlo51aKNI8IglKx60RYxS16ST9VXUeaX0vc3iLrAJs91s5gF3KIwFWuYvu2D6GAMHD1YnORbIjTHaJTexJSXebNvyLr8fhsYNp/WnBHrw4FttaxBVW55rJC55WuwVM3NUgnMDtod2TYrfjD2hrwlp3sdXG+gvA2/Y6BUaTaX3rCr71KfcZph/cuTbfbeCLQK2Ws/zJwl//vw80bAvC4XNT3L3MmjsMXiUqa6TB81w5TY0XUaQ9KjEn+tYHZkSMwSEztw2um6pvXSfNVGwJatk8fUXpjcmo1JcZujMtIa/uL+k8ryqDPuy38bxHnX9XcZICYocNt1WmqRiVS6GSMSlgPv9S0SClDA6veXacUWezGX6W6ilFJ+c9rt3io5qyf6jurT+2/OO8FoMEayRu1XVkA1B+FBWBmb2DId+3ppMVIrgi566BykboDwCyE91sEfoB5aTq8TYSUVAyBybUjwwpT/xClcfOxE6ow0kPT9NpHQAszCKCHH8wGMr/T8SYaH1MuzwC+YpwMjZYR9BwCOVwtNQdR5ceek6DqGYSROg/CSGw68zdYR5to="

branches:
  only:
    - source

#Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:/opt/ghc/$GHC_VERSION/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-head
      - ghc-7.10.3

install:
  - stack --no-terminal build  

script:
  - stack --no-terminal exec site build

after_script:
  - cd _site
  - git checkout -b master  
  - git config --global user.email "$GH_EMAIL"
  - git config --global user.name "$GH_NAME"  
  - export REMOTE=$(git config remote.origin.url | sed 's/.*:\/\///')
  - git remote add github https://${GH_USER}:${GH_TOKEN}@${REMOTE}
  - git add --all
  - git status
  - git commit -m "Built by Travis ( build $TRAVIS_BUILD_NUMBER )"
  - git push github master:master | grep -v http

