# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.    
language: c
env:
  global:
  - GHC_VERSION=7.10.3
  - secure: "Z0oYkfTm6TfPxKmVppFl9U20zAuwqoehiO8N8tgvay85jeVhBiC5hI5ZVGrEzn8lI9gLPLbixZCBOvZZ0R5t1lwaKyHHkF+EDAMV0ZECrj6tyvKPvCDjDISacHDMo+ghOWXc9/WAkZeu6wFU4FYOSP2BVgmu/PbOQSwjgwhmJczVGuk6b231wz2J8sz1GNo24NpHMRIOyCKkvbedIFQRk1QQP6QjJH25xlOwesZfBvIVRGaK9NlPFHZNhqyv1XPtYjwa2CSf1HxSfEoO5/ORml536mTiHd0dINnEJUClzUUo8eH4+iYAhQzMd+leitDOfP7N+PPblkgEay9i47exd8JD0BldyLzvUXh95IR1c/UUy+ksAdpBUmFQScjBhpxfXbdj1mpXYIzyqO3B9EW1K7UMWSiU5zF2GsHpFtMY7By55D7uxNB8uDkB0Oeln/JVo76dureuUTdAgbSjAV2Dcbs82jghCEqW2xo0RUCXb9e4LhqFfbXtDSGPGZ5zBPkeCpdjxe5Q7E3lnK1wWSfbHFGjU2/lVe7nU4YHIFu4Os+SadbV98/YwyTWt+PwleWh1IMuppHnllAJvLt2rchCmvYvqoOhgVf7qRwEG0L5y3/tPHJSoe1KCzPgg0kriIsxcMwVPk4q4OQSS2ZDgHLWhHl74sxdTDWrHY30QF8mHGs="

branches:
  only:
  - source

#Caching so the next build will be fast too.    
cache:
  directories:
  - "$HOME/.stack"

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:/opt/ghc/$GHC_VERSION/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - cabal-install-head
    - ghc-7.10.3

install:
- stack --no-terminal build

script:
- stack --no-terminal exec site build

after_script:
- cd _site
# Adding a CNAME file, so our custom domain works with github 
- echo "blog.${GH_USER}.com" > CNAME  
- git config --global user.email "$GH_EMAIL"
- git config --global user.name "$GH_NAME"
- export REMOTE=$(git config remote.origin.url | sed 's/.*:\/\///')
- git init  
- git remote add github https://${GH_USER}:${GH_TOKEN}@${REMOTE}
- git add --all
- git status
- git commit -m "Built by Travis ( build $TRAVIS_BUILD_NUMBER )"
# We don't care about commits to the master as a completely new site would be generated everytime  
- git push github master:master -f 2>&1 | grep -v http

notifications:
  email:
    recipients:
      - chopra.shubham+travis@gmail.com
    on_success: always
        
