# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.  
language: c

env:
  global:
  - GHC_VERSION=7.10.3
  secure: "bQqx8Q15Jx6mz0ZAAPiVxopQfrdGjtT2rpQjS6t3s+L9+39gwpgCMb3LmWDnLRale9GbdCs81oSjUB5NvZpWUF4/cMbe8yKBOnyioO/nU6sjexGNNJsahZwvx7DIT6eD9dAwecoTYGUvc7lKaxGMgQTtgTPU0WYStzxSM8584ulVWtKs6CBFbYXsn/NmvNvFMQSeDhG8l0DRrYrb2cbMqSvr6WZxJE0L5cU0MBCIvbrmlwFv+QWFMRcME7fjA/Q26QBL7XAvcaSYQpHAp5GcH7zF4HDNRUspNXRQw97XXCciS2pWCsU++k3G/BVol/D3F9sOu6f1gBoHOMgv5tH4MEaFchNT3nulKJra9l2wUzVxr1N43sCnSNKWHCdfYrnwjJJlqx14b4tZz0FbVwgPCJbkMBT+i+FzQoCP/sb6abopB7FXFf4vDsABSJEoXyNolziXQbLS6sJEGOxvr1+jQD92ztlrDIwdg73RwXQKINDSBPMG3yV6cwUEjYDPimrCIjKXZsHW5khd71DOQeAJlgI9uS6taaFDWZb/nJRj/tXvWKBcSvDFtZOIju9wdgQcAvBLyR0Zsif/2/+qzOmEZ//p5z1Xr69L22yTww1mVloWf0SDfM529nIjidJDlETrOrZAUEDDqw3sNxpnZhkv4ku+tqKgrhBE6DgfD65IZF4="

branches:
  only:
    - source

#Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:/opt/ghc/$GHC_VERSION/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-head
      - ghc-7.10.3

install:
  - stack --no-terminal build  

script:
  - stack --no-terminal exec site build

after_script:
  - cd _site
  - ls -al  
  - git --version  
  - git status  
  #Travis detaches the head, so we reinitialize git inside _site/  
  - export REMOTE=$(git config remote.origin.url | sed 's/.*:\/\///')
  - git init  
  - git config --global user.email "$GH_EMAIL"
  - git config --global user.name "$GH_NAME"  
  - git remote add github https://shubhamchopra:${GH_TOKEN}@${REMOTE}
  - git add --all
  - git status
  - git commit -m "Built by Travis ( build $TRAVIS_BUILD_NUMBER )"
  - git push github master:master | grep -v http

