# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.  
language: c

env:
  global:
  - GHC_VERSION=7.10.3
  - secure: "oVsZj/aRjDkPGAhRZ7t7X12h6d7YpV8XrSkq7Thax7RavhaxrJqmonSnvch0iAtLw7chYexS23cf5EET5uZKEtY+Ug6oDwR53tEZ4Btwxz8rVTUW39aLRagn+cdXTMSwARyY3KTxnCsG5rd/xRZPxIqqMg+pSNoZOxeIfWdI7QxKKD/rBnXC+slyuu+8An3dKkdySfmJthn8FFhSeHMJv3f1trVgGSP/GyhDQ89byu33xiRbat0oXmOX0RV5MtJETkFyupJdo9BjUnQq+91EU65wscCL19Gn44CYhCc6kAAPDBQkksRJWMjsei5dMtpAkdeAfCheqqPveDahVEKSroJ73WPkUrhOrV877ErY9iiiOkmBTsf4kqJ8a6ewXJ8RuUfC/MeRWEzCwhmOJLI2vSWLCM6C6ssOn4+Ny4x/8iYKWi5A8BFVlNhpUVYu6gGOdAxXhdIaHjhIZIPoPpcgRwafjObVtkFgg7HVATDkkn2Ir5nZ38gd5eX+4X0Zl2KWFWXFTW8oX4KZu/h24jhYoUwtKUCUCNWM9VdIjJDNH3JrkiSx4isQm4+n/Al4rT/LKqaErQ3jes0ED3leeC9uLS0yJeH31PUgxi69BKR2/K+WPRQsGCIb0pFBLGNfPueWNfELe9Qs+i9GTK+ExtmTkFDoQjsUmAqwUP/mkKivlrA="

branches:
  only:
    - source

#Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:/opt/ghc/$GHC_VERSION/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - cabal-install-head
      - ghc-7.10.3

install:
  - stack --no-terminal build  

script:
  - stack --no-terminal exec site build

after_script:
  - cd _site
  - ls -al  
  - git --version  
  - git status  
  #Travis detaches the head, so we reinitialize git inside _site/  
  - git init  
  - git config --global user.email "$GH_EMAIL"
  - git config --global user.name "$GH_NAME"  
  - export REMOTE=$(git config remote.origin.url | sed 's/.*:\/\///')
  - git remote add github https://shubhamchopra:${GH_TOKEN}@${REMOTE}
  - git add --all
  - git status
  - git commit -m "Built by Travis ( build $TRAVIS_BUILD_NUMBER )"
  - git push github master:master | grep -v http

